// react-client/src/components/Project/Dashboard.jsx
import { Link, useLocation, useNavigate } from "react-router-dom"
import useAxiosPrivate from "../../hooks/useAxiosPrivate"
import { useEffect, useState, useRef } from "react"
import useAuth from "../../hooks/useAuth"

const Dashboard = () => {
    const [projects, setProjects] = useState()
    const axiosPrivate = useAxiosPrivate()
    const navigate = useNavigate()
    const location = useLocation()
    const { setAuth } = useAuth()
    const [ isDeleted, setIsDeleted ] = useState(false)


    useEffect(() => {

        // to cancel request 
        const controller = new AbortController()

        const getProjects = async () => {
            try {
                const res = await axiosPrivate.get('/Project/', {
                    signal: controller.signal,
                })
                setProjects(res.data)
            }
            catch (err) {
                setAuth({})
                localStorage.clear()
                navigate('/login', { state: { from: location }, replace: true })
            }
        }

        getProjects()
        setIsDeleted(false)

    }, [isDeleted])

    const handleDelete = async (id) =>{
       const res = await axiosPrivate.delete(`/Project/${id}`)
       setIsDeleted(true)
    }

    return (
        <div className="px-4 sm:px-6 lg:px-8">
            <div className="mt-8 flow-root">
                <div className="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div className="inline-block min-w-full py-2 sm:px-6 lg:px-8">
                        <div className="overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:rounded-lg">
                            <table className="min-w-full divide-y divide-gray-300">
                                <thead className="bg-indigo-50">
                                    <tr>
                                        <th className="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Id
                                        </th>
                                        <th className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Name</th>
                                        <th className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Description</th>
                                        <th className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {
                                        projects?.length ?
                                            projects.map((p, i) =>
                                                <tr>
                                                    <td
                                                        className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6"> {p.id}
                                                    </td>
                                                    <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{p.name}</td>
                                                    <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{p.description}
                                                    </td>
                                                    <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                                                        <Link to={`/project/${p.id}/edit`}>edit </Link>
                                                        <button onClick={() => handleDelete(p.id)}>delete </button>
                                                        <Link to={`/project/${p.id}`}> details</Link>
                                                    </td>
                                                </tr>
                                            )
                                            : ''}
                                </tbody>
                            </table>
                        </div>
                        <div className="mt-3 font-semibold text-gray-900 ">
                            <Link to="/project/new"
                                className="font-bold text-xl py-1 px-2.5 m-1 shadow bg-indigo-50 ring-1 ring-black ring-opacity-5 rounded-full ">+</Link>
                        </div>
                    </div>
                </div>
            </div >
        </div >
    )
}

export default Dashboard

// client/src/app/components/dashboard/dashboard.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { NotifierService } from 'angular-notifier';
import { ApiProjectService } from 'src/app/services/api-project.service';
import { AuthService } from 'src/app/services/auth.service';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent {

  projects:any = []
  
  constructor(private apiProject:ApiProjectService,private notify:NotifierService){}

  ngOnInit(){
    this.getProjects()
  }

  getProjects(){
    this.apiProject.getAllProjects()
    .subscribe({ 
      next:(res)=>{this.projects = res},
      error:(err) => {
        console.log(err)
        this.notify.notify('error','Please login again')
      }
    })
  }

  deleteProject(id: number){
    this.apiProject.deleteProject(id)
    .subscribe({
      next:(res)=>{
        this.notify.notify('success','Project was deleted successfully')
        this.getProjects()
      },
      error:(err)=> {
        console.log(err)
        // if err.status == 403 
        this.notify.notify('error','Please login again')
      }
    })
  }

  
}

<div class="px-4 sm:px-6 lg:px-8">
    <div class="mt-8 flow-root">
        <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
                <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:rounded-lg">
                    <table class="min-w-full divide-y divide-gray-300">
                        <thead class="bg-indigo-50">
                            <tr>
                                <th class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Id
                                </th>
                                <th class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Name</th>
                                <th class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Description</th>
                                <th class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <ng-container *ngFor="let project of projects">
                                <tr>
                                    <td
                                        class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">
                                        {{project.id}}</td>
                                    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{project.name}}</td>
                                    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                                        {{project.description}}</td>
                                    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                                        <a [routerLink]="['/project',project.id,'edit']">edit </a>
                                        <button (click)="deleteProject(project.id)">delete </button>
                                        <a [routerLink]="['/project',project.id]"> details</a>
                                    </td>
                                </tr>
                            </ng-container>
                        </tbody>
                    </table>
                </div>
                <div class="mt-2 font-semibold text-gray-900 ">
                    <button routerLink="/project/new"
                        class="font-bold text-xl py-2 px-4 m-1 shadow bg-indigo-50 ring-1 ring-black ring-opacity-5 rounded-full ">+</button>
                </div>
            </div>
        </div>
    </div>
</div>
