// react-client/src/components/Project/ProjectForm.jsx
import { useEffect, useState } from "react"
import { Link } from "react-router-dom"

const ProjectForm = ({title, btn ,handleSubmit, prevProject}) => {
    const [project, setProject] = useState({
        name:'',
        description:''
    }) 

    useEffect(()=>{
        if (prevProject)
            setProject(prevProject)
    },[prevProject])
    

    const handleChanges = (e) =>{
        setProject({...project,[e.target.name]:e.target.value})
    }


    return (
        <div className="flex justify-center ">
            <form className="mt-10">

                <div className="border-b border-gray-900/10 pb-12">
                    <h2 className="text-base font-semibold leading-7 text-gray-900">{title}</h2>
                    <div className="mt-10 grid grid-cols-9 gap-x-9 gap-y-9 sm:grid-cols-6">
                        <div className="sm:col-span-12">
                            <label for="name" className="block text-sm font-medium leading-6 text-gray-900">Project name</label>
                            <div className="mt-2">
                                <div
                                    className="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
                                    <input type="text" name="name" id="name" value={project.name}
                                        autoComplete="name" onChange={handleChanges}
                                        className="pl-4 block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" />
                                </div>
                            </div>
                        </div>

                        <div className="sm:col-span-12">
                            <label for="description" className="block text-sm font-medium leading-6 text-gray-900">Project
                                Description</label>
                            <div className="mt-2">
                                <div
                                    className="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
                                    <textarea type="text" name="description" id="description" value={project.description}
                                        autoComplete="description" onChange={handleChanges}
                                        className="pl-4 block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="mt-6 flex items-center justify-end gap-x-6">
                    <Link className="text-sm font-semibold leading-6 text-gray-900" to="/">Cancel</Link>
                    <button type="submit" onClick={(e) => handleSubmit(e,project)}
                        className="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">{btn}</button>
                </div>
            </form>
        </div>
    )
}
export default ProjectForm

// client/src/app/components/project-form/project-form.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { NotifierService } from 'angular-notifier';
import { ApiProjectService } from 'src/app/services/api-project.service';

@Component({
  selector: 'app-project-form',
  templateUrl: './project-form.component.html',
  styleUrls: ['./project-form.component.css']
})
export class ProjectFormComponent {

  projectForm!: FormGroup
  isUpdate: boolean = false
  id!: number

  constructor(
    private fb: FormBuilder,
    private projectService: ApiProjectService,
    private router: Router,
    private activatedRouter: ActivatedRoute,
    private notify:NotifierService
  ) { }

  ngOnInit(): void {
    this.projectForm = this.fb.group({
      name: [''],
      description: ['']
    })

    if (this.activatedRouter.snapshot.params['id']) {
      this.activatedRouter.params.subscribe(val => {
        this.id = val['id']
        this.projectService.getProjectById(this.id)
          .subscribe(res => {
            this.isUpdate = true
            this.fillForm(res)
          })
      })
    }
  }

  onSubmit() {
    this.projectService.createProject(this.projectForm.value)
      .subscribe({
        next: (res) => {
          this.projectForm.reset()
          this.notify.notify('success','Project was created successfully')
          this.router.navigate(['dashboard'])
        },
        error: (err) => console.log(err.error)
      })

  }

  onUpdate() {
    console.log(this.projectForm.value)
    this.projectService.updateProject(this.projectForm.value, this.id)
      .subscribe({
        next: (res) => {
          this.projectForm.reset()
          this.notify.notify('success','Project was updated successfully')
          this.router.navigate(['dashboard'])
        },
        error: (err) => console.log(err.error)
      })
  }

  fillForm(project: any) {
    this.projectForm.setValue({
      name: project.name,
      description: project.description
    })
  }
}

<div class="flex justify-center ">
    <form class="mt-10" [formGroup]="projectForm">
        <!-- <div class="space-y-12"> -->
        <div class="border-b border-gray-900/10 pb-12">
            <h2 class="text-base font-semibold leading-7 text-gray-900">Create a new Project</h2>
            <div class="mt-10 grid grid-cols-9 gap-x-9 gap-y-9 sm:grid-cols-6">
                <div class="sm:col-span-12">
                    <label for="name" class="block text-sm font-medium leading-6 text-gray-900">Project name</label>
                    <div class="mt-2">
                        <div
                            class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
                            <input formControlName="name" type="text" name="name" id="name"
                                autocomplete="name"
                                class="pl-4 block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6">
                        </div>
                    </div>
                </div>

                <div class="sm:col-span-12">
                    <label for="description" class="block text-sm font-medium leading-6 text-gray-900">Project
                        Description</label>
                    <div class="mt-2">
                        <div
                            class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-indigo-600 sm:max-w-md">
                            <textarea formControlName="description" type="text" name="description" id="description"
                                autocomplete="description"
                                class="pl-4 block flex-1 border-0 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6"></textarea>
                        </div>
                    </div>
                </div>






            </div>
        </div>




        <!-- </div> -->

        <div class="mt-6 flex items-center justify-end gap-x-6">
            <a type="button" class="text-sm font-semibold leading-6 text-gray-900" routerLink="/dashboard">Cancel</a>
            <button type="submit" (click)="onSubmit()" *ngIf="!isUpdate, else update"
                class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Submit</button>
            <ng-template #update>
            <button type="submit" (click)="onUpdate()"
                class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Update</button>
            </ng-template>
        </div>
    </form>
</div>
